CREATE SCHEMA strategi AUTHORIZATION "postgres";
CREATE SCHEMA meridian2 AUTHORIZATION "postgres";
CREATE SCHEMA vmd AUTHORIZATION "postgres";
CREATE SCHEMA osmm AUTHORIZATION "postgres";
CREATE SCHEMA bdryline AUTHORIZATION "postgres";
CREATE SCHEMA other AUTHORIZATION "postgres";
